// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniErp.Infrastructure.Persistence.Modules.Migration;

#nullable disable

namespace MiniErp.Infrastructure.Persistence.Migrations.Mesp141
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260915053312_MESP141MasterReferenceExecution")]
    partial class MESP141MasterReferenceExecution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EvidenceConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<Guid?>("PreviousAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SafeOutcomeCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("AttemptId");

                    b.HasIndex("TenantId", "RunId", "PreviousAttemptId");

                    b.HasIndex("TenantId", "RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("MigrationAttempts", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewEntity", b =>
                {
                    b.Property<Guid>("PreviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ControlTotalsJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExceptionCount")
                        .HasColumnType("int");

                    b.Property<string>("FindingCountsJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("QuarantinedCount")
                        .HasColumnType("int");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalStagedRecords")
                        .HasColumnType("int");

                    b.Property<int>("UnresolvedDependencyCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ValidationAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PreviewId");

                    b.HasIndex("TenantId", "RunId", "AttemptId")
                        .IsUnique();

                    b.HasIndex("TenantId", "RunId", "ValidationAttemptId");

                    b.ToTable("MigrationDryRunPreviews", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewRowEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PreviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<int>("PlannedAction")
                        .HasColumnType("int");

                    b.Property<string>("Projection")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "PreviewId", "StagedRecordId");

                    b.HasIndex("TenantId", "RunId", "StagedRecordId");

                    b.ToTable("MigrationDryRunPreviewRows", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OwnerBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RunId", "RecordType")
                        .IsUnique()
                        .HasFilter("[State] IN (2, 3)");

                    b.ToTable("MigrationExecutionBatches", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionEffectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EffectStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerRowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<string>("ResultingResourceCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ResultingResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SafeCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("int");

                    b.Property<Guid>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RunId", "StagedRecordId");

                    b.HasIndex("TenantId", "RunId", "AttemptId", "RecordType");

                    b.HasIndex("TenantId", "RunId", "AttemptId", "StagedRecordId")
                        .IsUnique();

                    b.ToTable("MigrationExecutionEffects", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIdempotencyEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EvidenceConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ResultKind")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId", "Operation", "IdempotencyKey");

                    b.HasIndex("TenantId", "RunId", "Operation", "IdempotencyKey");

                    b.ToTable("MigrationIdempotency", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIntakeEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FingerprintVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SourceBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SourceConcurrencyVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceLength")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SourceObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SourceTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RunId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "RunId");

                    b.HasIndex("TenantId", "SourceObjectId");

                    b.ToTable("MigrationIntakes", "migration", t =>
                        {
                            t.HasCheckConstraint("CK_MigrationIntakes_SourceTenant_Matches_Tenant", "[SourceTenantId] = [TenantId]");
                        });
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("EvidenceConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SourceProfileId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceProfileVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RunId");

                    b.HasIndex("TenantId", "RunId")
                        .IsUnique();

                    b.ToTable("MigrationRuns", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", b =>
                {
                    b.Property<Guid>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalPayload")
                        .IsRequired()
                        .HasMaxLength(2000000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("int");

                    b.Property<string>("SourceSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StagedRecordId");

                    b.HasIndex("TenantId", "RunId", "PackageHash");

                    b.HasIndex("TenantId", "RunId", "SourceSequence")
                        .IsUnique();

                    b.ToTable("MigrationStagedRecords", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationFindingEntity", b =>
                {
                    b.Property<Guid>("FindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<Guid?>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FindingId");

                    b.HasIndex("TenantId", "RunId", "AttemptId");

                    b.ToTable("MigrationValidationFindings", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationRecordEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<string>("FindingCodesJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "RunId", "AttemptId", "StagedRecordId");

                    b.HasIndex("TenantId", "RunId", "StagedRecordId");

                    b.ToTable("MigrationValidationRecords", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationResultEntity", b =>
                {
                    b.Property<Guid>("ValidationResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FindingCountsJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("QuarantinedCount")
                        .HasColumnType("int");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalStagedRecords")
                        .HasColumnType("int");

                    b.HasKey("ValidationResultId");

                    b.ToTable("MigrationValidationResults", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "PreviousAttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "ValidationAttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewRowEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PreviewId")
                        .HasPrincipalKey("TenantId", "PreviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "StagedRecordId")
                        .HasPrincipalKey("TenantId", "RunId", "StagedRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionBatchEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionEffectEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "StagedRecordId")
                        .HasPrincipalKey("TenantId", "RunId", "StagedRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionBatchEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId", "RecordType")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId", "RecordType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIdempotencyEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIntakeEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationFindingEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationRecordEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationResultEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "StagedRecordId")
                        .HasPrincipalKey("TenantId", "RunId", "StagedRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationResultEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
