// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniErp.Infrastructure.Persistence.Modules.Migration;

#nullable disable

namespace MiniErp.Infrastructure.Persistence.Migrations.Mesp141
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260912224151_MESP141MigrationIntakeStaging")]
    partial class MESP141MigrationIntakeStaging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<Guid?>("PreviousAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SafeOutcomeCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("AttemptId");

                    b.HasIndex("TenantId", "RunId", "PreviousAttemptId");

                    b.HasIndex("TenantId", "RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("MigrationAttempts", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIdempotencyEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ResultKind")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId", "Operation", "IdempotencyKey");

                    b.HasIndex("TenantId", "RunId", "Operation", "IdempotencyKey");

                    b.ToTable("MigrationIdempotency", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIntakeEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FingerprintVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SourceBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SourceConcurrencyVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceLength")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SourceObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SourceTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RunId");

                    b.HasIndex("TenantId", "RunId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "SourceObjectId");

                    b.ToTable("MigrationIntakes", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceProfileId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceProfileVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RunId");

                    b.HasIndex("TenantId", "RunId")
                        .IsUnique();

                    b.ToTable("MigrationRuns", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "PreviousAttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIdempotencyEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIntakeEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
