// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniErp.Infrastructure.Persistence.Modules.Migration;

#nullable disable

namespace MiniErp.Infrastructure.Persistence.Migrations.Mesp141
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260924135807_Mesp141Slice11Reconciliation")]
    partial class Mesp141Slice11Reconciliation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EvidenceConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<Guid?>("PreviousAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SafeOutcomeCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("AttemptId");

                    b.HasIndex("TenantId", "RunId", "PreviousAttemptId");

                    b.HasIndex("TenantId", "RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("MigrationAttempts", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewEntity", b =>
                {
                    b.Property<Guid>("PreviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ControlTotalsJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExceptionCount")
                        .HasColumnType("int");

                    b.Property<string>("FindingCountsJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("QuarantinedCount")
                        .HasColumnType("int");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalStagedRecords")
                        .HasColumnType("int");

                    b.Property<int>("UnresolvedDependencyCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ValidationAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PreviewId");

                    b.HasIndex("TenantId", "RunId", "AttemptId")
                        .IsUnique();

                    b.HasIndex("TenantId", "RunId", "ValidationAttemptId");

                    b.ToTable("MigrationDryRunPreviews", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewRowEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PreviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<int>("PlannedAction")
                        .HasColumnType("int");

                    b.Property<string>("Projection")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "PreviewId", "StagedRecordId");

                    b.HasIndex("TenantId", "RunId", "StagedRecordId");

                    b.ToTable("MigrationDryRunPreviewRows", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationEconomicRepresentationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AppliedRate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ControlAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EffectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EvidenceConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EvidenceVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ExchangeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExchangeRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExchangeRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedFunctionalCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("FunctionalAmount")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid?>("MonetaryPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MonetaryPolicyVersionNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("OffsetAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OwnerModule")
                        .HasColumnType("int");

                    b.Property<string>("OwnerReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("OwnerSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostingRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PostingRuleVersionNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RateDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("ReportingAppliedRate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<string>("ReportingCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("ReportingExchangeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReportingExchangeRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ReportingExchangeRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("Reversal")
                        .HasColumnType("bit");

                    b.Property<string>("RoundingMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("RoundingScale")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceContract")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceEvent")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SourceEvidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceEvidenceVersion")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TransactionAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("TransactionCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RunId", "AttemptId", "EffectId", "OwnerModule", "Kind", "OwnerId", "EvidenceVersion")
                        .IsUnique();

                    b.ToTable("MigrationEconomicRepresentations", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OwnerBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RunId", "RecordType")
                        .IsUnique()
                        .HasFilter("[State] IN (1, 2, 3)");

                    b.ToTable("MigrationExecutionBatches", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionEffectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EffectStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerRowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<string>("ResultingResourceCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ResultingResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SafeCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("int");

                    b.Property<Guid>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RunId", "StagedRecordId");

                    b.HasIndex("TenantId", "RunId", "AttemptId", "RecordType");

                    b.HasIndex("TenantId", "RunId", "AttemptId", "StagedRecordId")
                        .IsUnique();

                    b.ToTable("MigrationExecutionEffects", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationHandoverReadinessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BusinessReady")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EvidenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Mesp48Complete")
                        .HasColumnType("bit");

                    b.Property<bool>("Mesp50Complete")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductionReady")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReconciliationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReconciliationVersion")
                        .HasColumnType("int");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TenantActivationPerformed")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReconciliationId", "ReconciliationVersion")
                        .IsUnique();

                    b.HasIndex("TenantId", "RunId", "AttemptId");

                    b.HasIndex("TenantId", "RunId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "RunId", "ReconciliationId");

                    b.ToTable("MigrationHandoverReadiness", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIdempotencyEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EvidenceConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ResultKind")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId", "Operation", "IdempotencyKey");

                    b.HasIndex("TenantId", "RunId", "Operation", "IdempotencyKey");

                    b.ToTable("MigrationIdempotency", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIntakeEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FingerprintVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SourceBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SourceConcurrencyVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceLength")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SourceObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SourceTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RunId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "RunId");

                    b.HasIndex("TenantId", "SourceObjectId");

                    b.ToTable("MigrationIntakes", "migration", t =>
                        {
                            t.HasCheckConstraint("CK_MigrationIntakes_SourceTenant_Matches_Tenant", "[SourceTenantId] = [TenantId]");
                        });
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationApprovalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("EvidenceConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EvidenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("ReconciliationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReconciliationVersion")
                        .HasColumnType("int");

                    b.Property<string>("RequirementKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RunId", "AttemptId");

                    b.HasIndex("TenantId", "RunId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "RunId", "ReconciliationId");

                    b.HasIndex("TenantId", "ReconciliationId", "ReconciliationVersion", "Domain", "RequirementKey", "ActorId")
                        .IsUnique();

                    b.ToTable("MigrationReconciliationApprovals", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AmountVariance")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("AppliedRate")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ControlAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Domain")
                        .HasColumnType("int");

                    b.Property<Guid?>("EffectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExchangeRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExchangeRateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExchangeRateVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FindingCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("FunctionalAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("FunctionalCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("GlControlAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LinkedAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("OpeningDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("OwnerReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("OwnerRoundingDifference")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid?>("OwnerSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostingRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PostingRuleVersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("QuantityVariance")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("ReconciliationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoundingMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("RoundingPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RoundingPolicyVersionNumber")
                        .HasColumnType("int");

                    b.Property<int?>("RoundingScale")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("SourceAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("SourceContract")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SourceCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("SourceCredit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("SourceDebit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("SourceEvent")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("SourceQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("SubsidiaryEstablishedAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("TargetAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("TargetCredit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("TargetDebit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal?>("TargetQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TransactionAmount")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("TransactionCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("UnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Variance")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RunId", "ReconciliationId");

                    b.HasIndex("TenantId", "ReconciliationId", "Domain", "ScopeKey")
                        .IsUnique();

                    b.ToTable("MigrationReconciliationDetails", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<bool>("ApprovalEnforcesSeparationOfDuties")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovalPolicyCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ApprovalPolicyEffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ApprovalPolicyEffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApprovalPolicyId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ApprovalPolicyVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("int");

                    b.Property<string>("EvidenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("QuarantinedCount")
                        .HasColumnType("int");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<int>("RequiredApprovalCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("SourceCredit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("SourceDebit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubmittedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetCredit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("TargetDebit")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnresolvedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Variance")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RunId", "AttemptId");

                    b.HasIndex("TenantId", "RunId", "EvidenceFingerprint")
                        .IsUnique();

                    b.HasIndex("TenantId", "RunId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "RunId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("MigrationReconciliations", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationRequirementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EligibleActorIdsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnforceSeparationOfDuties")
                        .HasColumnType("bit");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("ReconciliationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int");

                    b.Property<string>("RequirementKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RunId", "ReconciliationId");

                    b.HasIndex("TenantId", "ReconciliationId", "Domain", "RequirementKey")
                        .IsUnique();

                    b.ToTable("MigrationReconciliationRequirements", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("EvidenceConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SourceProfileId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceProfileVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RunId");

                    b.HasIndex("TenantId", "RunId")
                        .IsUnique();

                    b.ToTable("MigrationRuns", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", b =>
                {
                    b.Property<Guid>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalPayload")
                        .IsRequired()
                        .HasMaxLength(2000000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("int");

                    b.Property<string>("SourceSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StagedRecordId");

                    b.HasIndex("TenantId", "RunId", "PackageHash");

                    b.HasIndex("TenantId", "RunId", "SourceSequence")
                        .IsUnique();

                    b.ToTable("MigrationStagedRecords", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationFindingEntity", b =>
                {
                    b.Property<Guid>("FindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<Guid?>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FindingId");

                    b.HasIndex("TenantId", "RunId", "AttemptId");

                    b.ToTable("MigrationValidationFindings", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationRecordEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StagedRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<string>("FindingCodesJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "RunId", "AttemptId", "StagedRecordId");

                    b.HasIndex("TenantId", "RunId", "StagedRecordId");

                    b.ToTable("MigrationValidationRecords", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationResultEntity", b =>
                {
                    b.Property<Guid>("ValidationResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FindingCountsJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("QuarantinedCount")
                        .HasColumnType("int");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalStagedRecords")
                        .HasColumnType("int");

                    b.HasKey("ValidationResultId");

                    b.ToTable("MigrationValidationResults", "migration");
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "PreviousAttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "ValidationAttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewRowEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationDryRunPreviewEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PreviewId")
                        .HasPrincipalKey("TenantId", "PreviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "StagedRecordId")
                        .HasPrincipalKey("TenantId", "RunId", "StagedRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationEconomicRepresentationEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionEffectEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId", "EffectId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionBatchEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionEffectEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "StagedRecordId")
                        .HasPrincipalKey("TenantId", "RunId", "StagedRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationExecutionBatchEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId", "RecordType")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId", "RecordType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationHandoverReadinessEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "ReconciliationId")
                        .HasPrincipalKey("TenantId", "RunId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIdempotencyEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationIntakeEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationApprovalEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "ReconciliationId")
                        .HasPrincipalKey("TenantId", "RunId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationDetailEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "ReconciliationId")
                        .HasPrincipalKey("TenantId", "RunId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationRequirementEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationReconciliationEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "ReconciliationId")
                        .HasPrincipalKey("TenantId", "RunId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationFindingEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationRecordEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationResultEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationStagedRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "StagedRecordId")
                        .HasPrincipalKey("TenantId", "RunId", "StagedRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationValidationResultEntity", b =>
                {
                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId")
                        .HasPrincipalKey("TenantId", "RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniErp.Infrastructure.Persistence.Modules.Migration.MigrationAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RunId", "AttemptId")
                        .HasPrincipalKey("TenantId", "RunId", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
