#pragma warning disable CS1591

using System.Security.Cryptography;
using System.Text;
using MiniErp.App.BuildingBlocks.Tenancy;

namespace MiniErp.App.BuildingBlocks.Work;

/// <summary>Tenant-owned private-file metadata; object identity is opaque.</summary>
public sealed class PrivateFileMetadata : ITenantOwned
{
    internal PrivateFileMetadata(
        Guid objectId,
        TenantId tenantId,
        TenantWorkScope scope,
        string originalFileName,
        string contentType,
        long length,
        string sha256,
        DateTimeOffset createdAt,
        DateTimeOffset? expiresAt,
        PrivateFileSafetyRequirement safetyRequirement)
    {
        ObjectId = objectId;
        TenantId = tenantId;
        Scope = scope;
        OriginalFileName = originalFileName;
        ContentType = contentType;
        Length = length;
        Sha256 = sha256;
        CreatedAt = createdAt;
        ExpiresAt = expiresAt;
        Disposition = PrivateFileDisposition.Available;
        SafetyRequirement = safetyRequirement;
        ScanState = safetyRequirement == PrivateFileSafetyRequirement.TrustedGenerated
            ? PrivateFileScanState.NotApplicable
            : PrivateFileScanState.Unavailable;
        ConcurrencyVersion = 1;
    }

    public Guid ObjectId { get; }

    public TenantId TenantId { get; }

    public TenantWorkScope Scope { get; }

    public string OriginalFileName { get; }

    public string ContentType { get; }

    public long Length { get; internal set; }

    public string Sha256 { get; internal set; }

    public DateTimeOffset CreatedAt { get; }

    public DateTimeOffset? ExpiresAt { get; }

    public PrivateFileDisposition Disposition { get; internal set; }

    /// <summary>
    /// Distinguishes user-supplied content requiring external safety evidence
    /// from content generated by this server where malware scanning is not
    /// applicable. TrustedGenerated is accepted only from an explicit server
    /// producer and is never inferred from file content.
    /// </summary>
    public PrivateFileSafetyRequirement SafetyRequirement { get; }

    /// <summary>
    /// Honest scan state. The local adapter has no malware scanner and must
    /// never claim that an object is clean.
    /// </summary>
    public PrivateFileScanState ScanState { get; internal set; }

    public long ConcurrencyVersion { get; internal set; }
}

/// <summary>Safe result of private-file access.</summary>
public sealed class PrivateFileAccessResult
{
    private PrivateFileAccessResult(
        PrivateFileAccessOutcome outcome,
        PrivateFileMetadata? metadata,
        byte[]? content)
    {
        Outcome = outcome;
        Metadata = metadata;
        Content = content;
    }

    public PrivateFileAccessOutcome Outcome { get; }

    public PrivateFileMetadata? Metadata { get; }

    /// <summary>Content is returned only for an allowed same-Tenant read.</summary>
    public byte[]? Content { get; }

    public bool Allowed => Outcome == PrivateFileAccessOutcome.Allowed;

    internal static PrivateFileAccessResult AllowedResult(PrivateFileMetadata metadata, byte[] content) =>
        new(PrivateFileAccessOutcome.Allowed, metadata, content);

    internal static PrivateFileAccessResult Denied(PrivateFileAccessOutcome outcome) =>
        new(outcome, null, null);
}

/// <summary>
/// Safe result of a private-file overwrite. Unlike <see cref="PrivateFileAccessResult"/>,
/// this distinguishes a rejected precondition that left storage untouched from
/// a genuine mutation whose new content is quarantined pending external scan
/// evidence -- so a caller is never told a mutation failed when it actually
/// applied.
/// </summary>
public sealed class PrivateFileOverwriteResult
{
    private PrivateFileOverwriteResult(
        PrivateFileAccessOutcome outcome,
        bool mutated,
        PrivateFileMetadata? metadata,
        byte[]? content)
    {
        Outcome = outcome;
        Mutated = mutated;
        Metadata = metadata;
        Content = content;
    }

    public PrivateFileAccessOutcome Outcome { get; }

    /// <summary>
    /// True when this call actually replaced the stored bytes/metadata,
    /// regardless of whether the new content is safe to read yet. False for
    /// every precondition failure (foreign Tenant, missing object, expired,
    /// disposed, checksum failure, stale concurrency version), none of which
    /// touch storage.
    /// </summary>
    public bool Mutated { get; }

    /// <summary>
    /// Safe post-mutation metadata (including the new <see cref="PrivateFileMetadata.ConcurrencyVersion"/>
    /// and <see cref="PrivateFileMetadata.ScanState"/>) whenever <see cref="Mutated"/>
    /// is true; never populated for a non-mutating precondition failure.
    /// </summary>
    public PrivateFileMetadata? Metadata { get; }

    /// <summary>Content is returned only for an allowed same-Tenant overwrite whose
    /// safety requirement does not gate on external scan evidence. Never populated
    /// for quarantined content, even though the mutation itself succeeded.</summary>
    public byte[]? Content { get; }

    public bool Allowed => Outcome == PrivateFileAccessOutcome.Allowed;

    internal static PrivateFileOverwriteResult AllowedResult(PrivateFileMetadata metadata, byte[] content) =>
        new(PrivateFileAccessOutcome.Allowed, mutated: true, metadata, content);

    /// <summary>The mutation succeeded (new bytes, hash, length and concurrency
    /// version are already stored) but the replacement content requires fresh
    /// external scan evidence before it can be read, so no content is exposed.</summary>
    internal static PrivateFileOverwriteResult MutatedQuarantined(PrivateFileMetadata metadata) =>
        new(PrivateFileAccessOutcome.SafetyBlocked, mutated: true, metadata, content: null);

    /// <summary>A precondition failed before any mutation was attempted; storage is unchanged.</summary>
    internal static PrivateFileOverwriteResult Denied(PrivateFileAccessOutcome outcome) =>
        new(outcome, mutated: false, null, null);
}

/// <summary>Private object-storage abstraction with no public or anonymous path.</summary>
public interface IPrivateObjectStorage
{
    ValueTask<PrivateFileMetadata> StoreAsync(
        TenantContext tenantContext,
        TenantWorkScope scope,
        string originalFileName,
        string contentType,
        Stream content,
        DateTimeOffset? expiresAt = null,
        PrivateFileSafetyRequirement safetyRequirement = PrivateFileSafetyRequirement.ExternalScanRequired,
        CancellationToken cancellationToken = default);

    ValueTask<PrivateFileAccessResult> ReadAsync(
        TenantContext tenantContext,
        Guid objectId,
        CancellationToken cancellationToken = default);

    ValueTask<PrivateFileOverwriteResult> OverwriteAsync(
        TenantContext tenantContext,
        Guid objectId,
        long expectedConcurrencyVersion,
        Stream content,
        CancellationToken cancellationToken = default);
}

/// <summary>Honest file-safety state; provider-backed clean evidence is external.</summary>
public enum PrivateFileScanState
{
    NotScanned = 1,
    Pending = 2,
    Clean = 3,
    Rejected = 4,
    Unavailable = 5,
    NotApplicable = 6
}

/// <summary>Whether a private object requires scanner evidence before access.</summary>
public enum PrivateFileSafetyRequirement
{
    ExternalScanRequired = 1,
    TrustedGenerated = 2
}

/// <summary>
/// Deterministic local private-file adapter for tests/development only. It is
/// not a public object store and does not implement purge, signed URLs or
/// malware scanning.
/// </summary>
public sealed class InMemoryPrivateObjectStorage : IPrivateObjectStorage
{
    private readonly object syncRoot = new();
    private readonly Dictionary<Guid, (PrivateFileMetadata Metadata, byte[] Content)> objects = [];
    private readonly List<(TenantId TenantId, Guid ObjectId, PrivateFileAccessOutcome Outcome)> accessEvidence = [];
    private readonly TimeProvider timeProvider;

    public InMemoryPrivateObjectStorage(TimeProvider? timeProvider = null)
    {
        this.timeProvider = timeProvider ?? TimeProvider.System;
    }

    public async ValueTask<PrivateFileMetadata> StoreAsync(
        TenantContext tenantContext,
        TenantWorkScope scope,
        string originalFileName,
        string contentType,
        Stream content,
        DateTimeOffset? expiresAt = null,
        PrivateFileSafetyRequirement safetyRequirement = PrivateFileSafetyRequirement.ExternalScanRequired,
        CancellationToken cancellationToken = default)
    {
        ValidateContext(tenantContext, scope);
        ArgumentNullException.ThrowIfNull(content);
        var bytes = await ReadBytesAsync(content, cancellationToken);
        var safeName = SafeFileName(originalFileName);
        var safeType = SafeValue(contentType, nameof(contentType));
        if (!Enum.IsDefined(safetyRequirement))
        {
            throw new ArgumentOutOfRangeException(nameof(safetyRequirement));
        }

        var now = timeProvider.GetUtcNow();
        var metadata = new PrivateFileMetadata(
            Guid.NewGuid(),
            tenantContext.TenantId,
            scope,
            safeName,
            safeType,
            bytes.LongLength,
            Convert.ToHexString(SHA256.HashData(bytes)),
            now,
            expiresAt,
            safetyRequirement);
        lock (syncRoot)
        {
            objects.Add(metadata.ObjectId, (metadata, bytes));
            accessEvidence.Add((metadata.TenantId, metadata.ObjectId, PrivateFileAccessOutcome.Allowed));
        }

        return metadata;
    }

    public ValueTask<PrivateFileAccessResult> ReadAsync(
        TenantContext tenantContext,
        Guid objectId,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(tenantContext);
        if (objectId == Guid.Empty)
        {
            return ValueTask.FromResult(PrivateFileAccessResult.Denied(PrivateFileAccessOutcome.NotFound));
        }

        cancellationToken.ThrowIfCancellationRequested();
        lock (syncRoot)
        {
            if (!objects.TryGetValue(objectId, out var stored))
            {
                return ValueTask.FromResult(PrivateFileAccessResult.Denied(PrivateFileAccessOutcome.NotFound));
            }

            if (stored.Metadata.TenantId != tenantContext.TenantId)
            {
                // Internal audit evidence preserves the granular truth; the
                // caller-visible outcome always folds to NotFound so a foreign
                // object can never be distinguished from a missing one (M-1).
                accessEvidence.Add((tenantContext.TenantId, objectId, PrivateFileAccessOutcome.TenantDenied));
                return ValueTask.FromResult(PrivateFileAccessResult.Denied(PrivateFileAccessOutcome.NotFound));
            }

            if (EvaluateLifecycleOutcome(stored.Metadata, timeProvider.GetUtcNow()) is { } lifecycleOutcome)
            {
                accessEvidence.Add((tenantContext.TenantId, objectId, lifecycleOutcome));
                return ValueTask.FromResult(PrivateFileAccessResult.Denied(lifecycleOutcome));
            }

            var checksum = Convert.ToHexString(SHA256.HashData(stored.Content));
            if (!string.Equals(checksum, stored.Metadata.Sha256, StringComparison.OrdinalIgnoreCase))
            {
                stored.Metadata.Disposition = PrivateFileDisposition.ChecksumFailed;
                accessEvidence.Add((tenantContext.TenantId, objectId, PrivateFileAccessOutcome.ChecksumFailed));
                return ValueTask.FromResult(PrivateFileAccessResult.Denied(PrivateFileAccessOutcome.ChecksumFailed));
            }

            if (stored.Metadata.SafetyRequirement == PrivateFileSafetyRequirement.ExternalScanRequired
                && stored.Metadata.ScanState != PrivateFileScanState.Clean)
            {
                accessEvidence.Add((tenantContext.TenantId, objectId, PrivateFileAccessOutcome.SafetyBlocked));
                return ValueTask.FromResult(PrivateFileAccessResult.Denied(PrivateFileAccessOutcome.SafetyBlocked));
            }

            accessEvidence.Add((tenantContext.TenantId, objectId, PrivateFileAccessOutcome.Allowed));
            return ValueTask.FromResult(PrivateFileAccessResult.AllowedResult(stored.Metadata, stored.Content.ToArray()));
        }
    }

    public async ValueTask<PrivateFileOverwriteResult> OverwriteAsync(
        TenantContext tenantContext,
        Guid objectId,
        long expectedConcurrencyVersion,
        Stream content,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(tenantContext);
        ArgumentNullException.ThrowIfNull(content);
        if (expectedConcurrencyVersion < 1)
        {
            return PrivateFileOverwriteResult.Denied(PrivateFileAccessOutcome.ConcurrencyConflict);
        }

        var bytes = await ReadBytesAsync(content, cancellationToken);
        lock (syncRoot)
        {
            if (!objects.TryGetValue(objectId, out var stored))
            {
                return PrivateFileOverwriteResult.Denied(PrivateFileAccessOutcome.NotFound);
            }

            if (stored.Metadata.TenantId != tenantContext.TenantId)
            {
                // Same fold as ReadAsync: a foreign object must not be
                // distinguishable from a missing one to the caller (M-1).
                accessEvidence.Add((tenantContext.TenantId, objectId, PrivateFileAccessOutcome.TenantDenied));
                return PrivateFileOverwriteResult.Denied(PrivateFileAccessOutcome.NotFound);
            }

            // An object in any prohibited lifecycle state fails closed instead
            // of being silently overwritten (M-4), reported with its exact
            // classification rather than a generic Expired (M93-02). None of
            // these preconditions mutate storage.
            if (EvaluateLifecycleOutcome(stored.Metadata, timeProvider.GetUtcNow()) is { } lifecycleOutcome)
            {
                accessEvidence.Add((tenantContext.TenantId, objectId, lifecycleOutcome));
                return PrivateFileOverwriteResult.Denied(lifecycleOutcome);
            }

            var existingChecksum = Convert.ToHexString(SHA256.HashData(stored.Content));
            if (!string.Equals(existingChecksum, stored.Metadata.Sha256, StringComparison.OrdinalIgnoreCase))
            {
                stored.Metadata.Disposition = PrivateFileDisposition.ChecksumFailed;
                accessEvidence.Add((tenantContext.TenantId, objectId, PrivateFileAccessOutcome.ChecksumFailed));
                return PrivateFileOverwriteResult.Denied(PrivateFileAccessOutcome.ChecksumFailed);
            }

            if (stored.Metadata.ConcurrencyVersion != expectedConcurrencyVersion)
            {
                accessEvidence.Add((tenantContext.TenantId, objectId, PrivateFileAccessOutcome.ConcurrencyConflict));
                return PrivateFileOverwriteResult.Denied(PrivateFileAccessOutcome.ConcurrencyConflict);
            }

            // From here on the mutation is applied unconditionally: the new
            // bytes, hash, length and concurrency version are authoritative
            // regardless of what the safety-requirement branch below reports.
            objects[objectId] = (stored.Metadata, bytes);
            stored.Metadata.Length = bytes.LongLength;
            stored.Metadata.Sha256 = Convert.ToHexString(SHA256.HashData(bytes));
            stored.Metadata.ConcurrencyVersion++;

            if (stored.Metadata.SafetyRequirement == PrivateFileSafetyRequirement.ExternalScanRequired)
            {
                // Replacement bytes are new content. Never carry forward a
                // prior Clean decision, and never let this local adapter
                // fabricate scanner approval. The mutation above already
                // succeeded, so this reports quarantine, not mutation
                // failure -- the caller must not be told to retry a write
                // that already applied (HOLD-140-C).
                stored.Metadata.ScanState = PrivateFileScanState.Unavailable;
                accessEvidence.Add((tenantContext.TenantId, objectId, PrivateFileAccessOutcome.SafetyBlocked));
                return PrivateFileOverwriteResult.MutatedQuarantined(stored.Metadata);
            }

            accessEvidence.Add((tenantContext.TenantId, objectId, PrivateFileAccessOutcome.Allowed));
            return PrivateFileOverwriteResult.AllowedResult(stored.Metadata, bytes.ToArray());
        }
    }

    /// <summary>Test-only tamper hook; no production caller can access it.</summary>
    internal void TamperForValidation(Guid objectId, byte[] content)
    {
        ArgumentNullException.ThrowIfNull(content);
        lock (syncRoot)
        {
            if (objects.TryGetValue(objectId, out var stored))
            {
                objects[objectId] = (stored.Metadata, content.ToArray());
            }
        }
    }

    internal IReadOnlyList<(TenantId TenantId, Guid ObjectId, PrivateFileAccessOutcome Outcome)> AccessEvidence =>
        accessEvidence.ToArray();

    internal bool ExistsForValidation(Guid objectId)
    {
        lock (syncRoot)
        {
            return objects.ContainsKey(objectId);
        }
    }

    /// <summary>
    /// Evaluates the exact already-recorded lifecycle outcome for a same-Tenant
    /// object, without mutating anything. Checked in disposition-priority
    /// order so a previously recorded <see cref="PrivateFileDisposition.ChecksumFailed"/>
    /// or <see cref="PrivateFileDisposition.Disposed"/> state is always
    /// reported with its exact classification rather than being folded into
    /// the generic <see cref="PrivateFileAccessOutcome.Expired"/> outcome
    /// (M93-02). Returns <see langword="null"/> when the object is Available
    /// and unexpired, meaning the caller may proceed to the live checksum
    /// check.
    /// </summary>
    private static PrivateFileAccessOutcome? EvaluateLifecycleOutcome(PrivateFileMetadata metadata, DateTimeOffset now)
    {
        if (metadata.Disposition == PrivateFileDisposition.ChecksumFailed)
        {
            return PrivateFileAccessOutcome.ChecksumFailed;
        }

        if (metadata.Disposition == PrivateFileDisposition.Disposed)
        {
            return PrivateFileAccessOutcome.Disposed;
        }

        if (metadata.Disposition == PrivateFileDisposition.Expired || metadata.ExpiresAt <= now)
        {
            return PrivateFileAccessOutcome.Expired;
        }

        return null;
    }

    private static void ValidateContext(TenantContext tenantContext, TenantWorkScope scope)
    {
        ArgumentNullException.ThrowIfNull(tenantContext);
        ArgumentNullException.ThrowIfNull(scope);
        if (scope.TenantId != tenantContext.TenantId)
        {
            throw new ArgumentException("File scope must belong to the trusted Tenant.", nameof(scope));
        }
    }

    private static async Task<byte[]> ReadBytesAsync(Stream content, CancellationToken cancellationToken)
    {
        await using var buffer = new MemoryStream();
        await content.CopyToAsync(buffer, cancellationToken);
        return buffer.ToArray();
    }

    /// <summary>
    /// Unicode bidirectional-override, embedding, isolate and other deceptive
    /// formatting characters that must never appear in a filename (M-5). Valid
    /// Arabic letters, digits and normalized Unicode text are unaffected --
    /// none of these code points are Arabic script. Deliberately excludes
    /// U+200C (ZERO WIDTH NON-JOINER) and U+200D (ZERO WIDTH JOINER): both
    /// have legitimate shaping uses in Arabic-script text and are outside the
    /// approved rejection policy (L93-01) -- only the code points below are
    /// rejected.
    /// </summary>
    private static readonly char[] UnsafeFormatCharacters =
    [
        (char)0x200B, // zero width space
        (char)0x200E, // left-to-right mark
        (char)0x200F, // right-to-left mark
        (char)0x2060, // word joiner
        (char)0x202A, // left-to-right embedding
        (char)0x202B, // right-to-left embedding
        (char)0x202C, // pop directional formatting
        (char)0x202D, // left-to-right override
        (char)0x202E, // right-to-left override
        (char)0x2066, // left-to-right isolate
        (char)0x2067, // right-to-left isolate
        (char)0x2068, // first strong isolate
        (char)0x2069, // pop directional isolate
        (char)0xFEFF  // zero width no-break space / byte order mark
    ];

    private static string SafeFileName(string value)
    {
        ArgumentNullException.ThrowIfNull(value);

        // Normalize composed/decomposed Unicode to one comparable form before
        // validation. A path separator anywhere in the supplied name fails
        // closed rather than being silently truncated to a leaf name -- a
        // caller-supplied value that looks like a path is rejected outright,
        // never tolerantly reinterpreted as one (M-5). Only the exact reserved
        // names "." and ".." are rejected as traversal; separators are already
        // rejected outright, so an embedded ".." substring (e.g.
        // "report..final.txt") is a legitimate filename, not traversal
        // (L93-01).
        var name = value.Normalize(NormalizationForm.FormC);
        if (string.IsNullOrWhiteSpace(name)
            || name.Length > 255
            || name is "." or ".."
            || name.Contains('/')
            || name.Contains('\\')
            || name.Any(char.IsControl)
            || name.Any(UnsafeFormatCharacters.Contains))
        {
            throw new ArgumentException("Original filename is invalid or unsafe.", nameof(value));
        }

        return name;
    }

    private static string SafeValue(string value, string name)
    {
        if (string.IsNullOrWhiteSpace(value) || value.Trim().Length > 128 || value.Any(char.IsControl))
        {
            throw new ArgumentException("Value is invalid or unsafe.", name);
        }

        return value.Trim();
    }
}
