import { PageHeaderComponent } from '../../shared/ui/page-header.component';
import { CommonModule } from '@angular/common';
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { LanguageService } from '../../core/i18n/language.service';
import { MasterDataService } from '../master-data/master-data.service';
import { ProductRecord, UnitOfMeasureRecord } from '../master-data/master-data.models';
import { InventoryService } from './inventory.service';
import { InventoryStockControlComponent } from './inventory-stock-control.component';
import { InventoryAvailability, InventoryCustomerReturnBoundary, InventoryMovement, InventoryOpeningBalance, InventoryOpeningCreateRequest, InventoryReservation, InventoryReservationCreateRequest, InventoryTransfer, InventoryTransferCreateRequest, InventoryWarehouseOption } from './inventory.model';
import { DataGridAction, DataGridColumn, DataGridComponent } from '../../shared/ui/data-grid.component';

const movementLabels = {
  transferTitle: { en: 'Transfers', ar: '\u062a\u062d\u0648\u064a\u0644\u0627\u062a' }, transferLead: { en: 'Immutable quantity evidence.', ar: '\u062f\u0644\u064a\u0644 \u0643\u0645\u064a\u0629.' }, valuationTitle: { en: 'Moving Weighted Average', ar: '\u0627\u0644\u0645\u062a\u0648\u0633\u0637 \u0627\u0644\u0645\u062a\u062d\u0631\u0643 \u0627\u0644\u0645\u0631\u062c\u062d' }, valuationLead: { en: 'Explainable cost trail and reconciliation.', ar: '\u0645\u0633\u0627\u0631 \u062a\u0643\u0644\u0641\u0629 \u0642\u0627\u0628\u0644 \u0644\u0644\u062a\u0641\u0633\u064a\u0631 \u0648\u0627\u0644\u062a\u0633\u0648\u064a\u0629.' }, immutableEvidence: { en: 'Immutable', ar: '\u063a\u064a\u0631 \u0642\u0627\u0628\u0644 \u0644\u0644\u062a\u0639\u062f\u064a\u0644' }, sourceWarehouse: { en: 'Source', ar: '\u0627\u0644\u0645\u0635\u062f\u0631' }, destinationWarehouse: { en: 'Destination', ar: '\u0627\u0644\u0648\u062c\u0647\u0629' }, chooseDestination: { en: 'Choose destination', ar: '\u0627\u062e\u062a\u0631 \u0627\u0644\u0648\u062c\u0647\u0629' }, transferMode: { en: 'Mode', ar: '\u0627\u0644\u0646\u0645\u0637' }, directTransfer: { en: 'Direct', ar: '\u0645\u0628\u0627\u0634\u0631' }, inTransitTransfer: { en: 'Two-step', ar: '\u062e\u0637\u0648\u062a\u0627\u0646' }, createTransfer: { en: 'Create transfer', ar: '\u0625\u0646\u0634\u0627\u0621' }, ship: { en: 'Ship', ar: '\u0634\u062d\u0646' }, receive: { en: 'Receive', ar: '\u0627\u0633\u062a\u0644\u0627\u0645' }, receiveQuantity: { en: 'Received quantity', ar: '\u0627\u0644\u0643\u0645\u064a\u0629' }, resolveShortage: { en: 'Resolve loss', ar: '\u062a\u0633\u0648\u064a\u0629 \u0641\u0642\u062f' }, noTransfers: { en: 'No transfers', ar: '\u0644\u0627 \u062a\u062d\u0648\u064a\u0644\u0627\u062a' }, goodsReceiptPosting: { en: 'Goods Receipt', ar: '\u0627\u0633\u062a\u0644\u0627\u0645 \u0628\u0636\u0627\u0639\u0629' }, goodsReceiptPostingLead: { en: 'Accepted Recorded quantity only.', ar: '\u0627\u0644\u0645\u0642\u0628\u0648\u0644 \u0641\u0642\u0637.' }, supplierReturnPosting: { en: 'Supplier Return', ar: '\u0625\u0631\u062c\u0627\u0639 \u0645\u0648\u0631\u062f' }, supplierReturnPostingLead: { en: 'Eligible Awaiting Inventory source only.', ar: '\u0645\u0635\u062f\u0631 \u0645\u0624\u0647\u0644 \u0641\u0642\u0637.' }, customerReturnPosting: { en: 'Customer Return', ar: '\u0625\u0631\u062c\u0627\u0639 \u0639\u0645\u064a\u0644' }, customerReturnPostingLead: { en: 'Requires a Sales handoff.', ar: '\u064a\u062a\u0637\u0644\u0628 \u062a\u0633\u0644\u064a\u0645 \u0627\u0644\u0645\u0628\u064a\u0639\u0627\u062a.' },
} as const;

@Component({
  selector: 'app-inventory-workspace',
  standalone: true,
  imports: [PageHeaderComponent, CommonModule, FormsModule, RouterLink, InventoryStockControlComponent, DataGridComponent],
  template: `
    <section class="ui-page inventory-page" data-testid="inventory-workspace">
      <app-page-header class="page-header">
        <div page-header-copy><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h1>{{ text('inventoryTitle') }}</h1><p class="lede">{{ text('inventoryLead') }}</p></div>
          <div page-header-actions>
        <div class="header-actions"><a class="button button--secondary" routerLink="/app/inventory/valuation">{{ movementText('valuationTitle') }}</a><a class="button button--secondary" routerLink="/app">{{ language.text('overview') }}</a></div>
      
          </div>
        </app-page-header>perationalContext') }}</h2></div><span class="status-badge status-badge--active">{{ text('serverAuthority') }}</span></div>
        <div class="form-grid">
          <label><span>{{ text('selectWarehouse') }}</span><select [(ngModel)]="selectedWarehouseId" (ngModelChange)="onWarehouseChanged()"><option value="">{{ text('selectWarehouse') }}</option>@for (warehouse of warehouses(); track warehouse.warehouseId) {<option [value]="warehouse.warehouseId">{{ warehouse.displayName }}</option>}</select></label>
          <label><span>{{ text('product') }}</span><select [(ngModel)]="selectedProductId" (ngModelChange)="loadAvailability()"><option value="">{{ text('selectProduct') }}</option>@for (product of products(); track product.id) {<option [value]="product.id">{{ product.sku }} — {{ product.englishName || product.arabicName }}</option>}</select></label>
          <label><span>{{ text('unitOfMeasure') }}</span><select [(ngModel)]="selectedUnitId"><option value="">{{ text('selectUnit') }}</option>@for (unit of units(); track unit.id) {<option [value]="unit.id">{{ unit.code }} — {{ unit.englishName || unit.arabicName }}</option>}</select></label>
        </div>
      </section>

      <div class="inventory-grid">
        <section class="ui-surface availability-card">
          <div class="section-heading"><div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h2>{{ text('onHand') }}</h2></div><span class="metric-icon">◈</span></div>
          @if (availability(); as stock) {<div class="metric-grid"><div><small>{{ text('onHand') }}</small><strong>{{ stock.onHandQuantity | number:'1.0-4' }}</strong><span>{{ stock.unitOfMeasureCode || text('baseUnit') }}</span></div><div><small>{{ text('reserved') }}</small><strong>{{ stock.reservedQuantity | number:'1.0-4' }}</strong><span>{{ text('reserved') }}</span></div><div class="metric-grid__accent"><small>{{ text('available') }}</small><strong>{{ stock.availableQuantity | number:'1.0-4' }}</strong><span>{{ text('available') }}</span></div><div><small>{{ text('expected') }}</small><strong>{{ stock.expectedQuantity | number:'1.0-4' }}</strong></div><div><small>{{ text('damaged') }}</small><strong>{{ stock.damagedQuantity | number:'1.0-4' }}</strong></div><div><small>{{ text('inTransit') }}</small><strong>{{ stock.inTransitQuantity | number:'1.0-4' }}</strong></div></div>} @else {<p class="empty-copy">{{ text('noRecordsLead') }}</p>}
        </section>
        <section class="ui-surface ledger-card"><div class="section-heading"><div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h2>{{ text('inventoryTitle') }}</h2></div><span class="status-badge status-badge--active">{{ text('serverAuthority') }}</span></div><app-data-grid [rows]="movements()" [columns]="movementColumns" [rowActions]="[]" [language]="language.language()" [caption]="text('inventoryTitle')" [countLabel]="gridLabel('count')" [emptyLabel]="text('noRecordsLead')" [filterInputLabel]="gridLabel('filter')" [allValuesLabel]="gridLabel('all')" [clearFiltersLabel]="gridLabel('clear')" [pageSize]="movements().length || 1" [showPager]="false" />
        </section>
      </div>

      <div class="inventory-grid inventory-grid--lower">
        <section class="ui-surface workflow-card"><div class="section-heading"><div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h2>{{ text('inventoryTitle') }}</h2></div></div><form (ngSubmit)="createOpening()" class="form-grid"><label><span>{{ text('sourceLineage') }}</span><input name="sourceOwner" [(ngModel)]="opening.sourceOwner" required /></label><label><span>{{ text('sourceSystem') }}</span><input name="sourceSystem" [(ngModel)]="opening.sourceSystem" required /></label><label><span>{{ text('dateColumn') }}</span><input name="asOfDate" type="date" [(ngModel)]="opening.asOfDate" required /></label><label><span>{{ text('quantity') }}</span><input name="quantity" type="number" min="0.00000001" step="any" [(ngModel)]="opening.quantity" required /></label><label><span>{{ text('unitCost') }}</span><input name="unitCost" type="number" min="0" step="any" [(ngModel)]="opening.unitCost" required /></label><label><span>{{ text('currency') }}</span><input name="currency" maxlength="16" [(ngModel)]="opening.currencyCode" required /></label><label class="form-grid__wide"><span>{{ text('sourceReference') }}</span><input name="sourceReference" [(ngModel)]="opening.sourceReference" required /></label><button class="button button--primary" type="submit" [disabled]="!canCreate()">{{ text('createRecord') }}</button></form><app-data-grid [rows]="openings()" [columns]="openingColumns" [rowActions]="openingActions" [language]="language.language()" [caption]="text('inventoryTitle')" [countLabel]="gridLabel('count')" [emptyLabel]="text('noRecords')" [filterInputLabel]="gridLabel('filter')" [allValuesLabel]="gridLabel('all')" [clearFiltersLabel]="gridLabel('clear')" [pageSize]="openings().length || 1" [showPager]="false" (rowAction)="runOpeningAction($event)" /></section>
        <section class="ui-surface workflow-card"><div class="section-heading"><div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h2>{{ text('inventoryTitle') }}</h2></div><span class="status-badge status-badge--active">{{ text('doesNotReduceStock') }}</span></div><form (ngSubmit)="createReservation()" class="form-grid"><label><span>{{ text('quantity') }}</span><input name="requestedQuantity" type="number" min="0.00000001" step="any" [(ngModel)]="reservation.requestedQuantity" required /></label><label><span>{{ text('sourceType') }}</span><input name="sourceType" [(ngModel)]="reservation.sourceType" required /></label><label><span>{{ text('sourceReference') }}</span><input name="sourceReference" [(ngModel)]="reservation.sourceReference" required /></label><label class="checkbox-label"><input name="partial" type="checkbox" [(ngModel)]="reservation.allowPartialAllocation" /><span>{{ text('allowPartial') }}</span></label>@if (trackingEnabled()) {<label class="form-grid__wide"><span>{{ text('trackingIdentity') }}</span><input name="trackingIdentity" [(ngModel)]="reservation.trackingIdentity" required /></label>}<button class="button button--primary" type="submit" [disabled]="!canReserve()">{{ text('createRecord') }}</button></form><ng-template #reservationActions let-record><label class="inline-action"><span class="sr-only">{{ text('quantity') }}</span><input [name]="'reduce-' + record.id" type="number" min="0.00000001" step="any" [max]="record.reservedQuantity" [(ngModel)]="reductionQuantities[record.id]" [ngModelOptions]="{standalone: true}" [attr.aria-label]="text('quantity')" /><button class="button button--quiet" type="button" (click)="reduceReservation(record)">{{ text('reduce') }}</button><button class="button button--quiet" type="button" (click)="releaseReservation(record)">{{ text('release') }}</button></label></ng-template><app-data-grid [rows]="reservations()" [columns]="reservationColumns" [rowActionsTemplate]="reservationActions" [language]="language.language()" [caption]="text('inventoryTitle')" [countLabel]="gridLabel('count')" [emptyLabel]="text('noRecords')" [filterInputLabel]="gridLabel('filter')" [allValuesLabel]="gridLabel('all')" [clearFiltersLabel]="gridLabel('clear')" [pageSize]="reservations().length || 1" [showPager]="false" /></section>
      </div>

      <section class="ui-surface workflow-card movement-workflows">
        <div class="section-heading"><div><p class="eyebrow">{{ text('inventoryNavLabel') }}</p><h2>{{ movementText('transferTitle') }}</h2><p class="lede">{{ movementText('transferLead') }}</p></div><span class="status-badge status-badge--active">{{ movementText('immutableEvidence') }}</span></div>
        <form (ngSubmit)="createTransfer()" class="form-grid">
          <label><span>{{ movementText('sourceWarehouse') }}</span><select name="sourceWarehouse" [(ngModel)]="transfer.sourceWarehouseId" required>@for (warehouse of warehouses(); track warehouse.warehouseId) {<option [value]="warehouse.warehouseId">{{ warehouse.displayName }}</option>}</select></label>
          <label><span>{{ movementText('destinationWarehouse') }}</span><select name="destinationWarehouse" [(ngModel)]="transfer.destinationWarehouseId" required><option value="">{{ movementText('chooseDestination') }}</option>@for (warehouse of warehouses(); track warehouse.warehouseId) {<option [value]="warehouse.warehouseId">{{ warehouse.displayName }}</option>}</select></label>
          <label><span>{{ text('quantity') }}</span><input name="transferQuantity" type="number" min="0.00000001" step="any" [(ngModel)]="transfer.quantity" required /></label>
          <label><span>{{ movementText('transferMode') }}</span><select name="transferMode" [(ngModel)]="transfer.mode"><option value="Direct">{{ movementText('directTransfer') }}</option><option value="InTransit">{{ movementText('inTransitTransfer') }}</option></select></label>
          <label class="form-grid__wide"><span>{{ text('lifecycleReason') }}</span><input name="transferReason" maxlength="2048" [(ngModel)]="transfer.reason" /></label>
          <button class="button button--primary" type="submit" [disabled]="!canCreateTransfer()">{{ movementText('createTransfer') }}</button>
        </form>
        <app-data-grid [rows]="transfers()" [columns]="transferColumns" [rowActions]="transferActions" [language]="language.language()" [caption]="movementText('transferTitle')" [countLabel]="gridLabel('count')" [emptyLabel]="movementText('noTransfers')" [filterInputLabel]="gridLabel('filter')" [allValuesLabel]="gridLabel('all')" [clearFiltersLabel]="gridLabel('clear')" [pageSize]="transfers().length || 1" [showPager]="false" (rowAction)="runTransferAction($event)" />
        <div class="boundary-note movement-boundary"><strong>{{ movementText('goodsReceiptPosting') }}</strong><span>{{ movementText('goodsReceiptPostingLead') }}</span><strong>{{ movementText('supplierReturnPosting') }}</strong><span>{{ movementText('supplierReturnPostingLead') }}</span><strong>{{ movementText('customerReturnPosting') }}</strong><span>{{ movementText('customerReturnPostingLead') }}</span></div>
      </section>
      <app-inventory-stock-control></app-inventory-stock-control>
    </section>
  `,
  styles: [`.inventory-page{--inventory-ink:#18312d}.inventory-controls,.availability-card,.ledger-card,.workflow-card{padding:1.35rem}.inventory-grid{display:grid;grid-template-columns:minmax(0,.85fr) minmax(0,1.4fr);gap:1rem;margin-top:1rem}.inventory-grid--lower{grid-template-columns:repeat(2,minmax(0,1fr))}.section-heading{display:flex;justify-content:space-between;align-items:start;gap:1rem;margin-bottom:1rem}.section-heading h2{margin:.2rem 0}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}.form-grid label{display:grid;gap:.3rem;color:var(--muted);font-size:.78rem;font-weight:700}.form-grid input,.form-grid select{width:100%;border:1px solid #d7e0dd;border-radius:.55rem;padding:.65rem;background:#fff;color:var(--inventory-ink)}.form-grid__wide{grid-column:1/-1}.checkbox-label{display:flex!important;align-items:center;grid-template-columns:auto 1fr;gap:.5rem}.checkbox-label input{width:auto}.metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.6rem}.metric-grid>div{padding:1rem;background:#f4f8f6;border-radius:.7rem}.metric-grid small,.metric-grid span{display:block;color:var(--muted);font-size:.72rem}.metric-grid strong{display:block;font-size:1.65rem;color:var(--inventory-ink);margin:.25rem 0}.metric-grid__accent{background:#e4f2ed!important}.table-wrap{overflow:auto}.ui-grid{width:100%;border-collapse:collapse}.ui-grid th,.ui-grid td{padding:.7rem;border-bottom:1px solid #e8efec;text-align:start;font-size:.78rem;white-space:nowrap}.ui-grid th{color:var(--muted);font-size:.7rem;text-transform:uppercase;letter-spacing:.04em}.ui-grid small,.record-row small{display:block;color:var(--muted);margin-top:.2rem}.numeric{text-align:end!important}.record-list{display:grid;gap:.55rem;margin-top:1rem}.record-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:.7rem;align-items:center;border-top:1px solid #e8efec;padding-top:.7rem}.record-actions{display:flex;gap:.4rem}.inline-action{display:flex!important;align-items:center;gap:.35rem}.inline-action input{width:5.5rem!important;padding:.45rem!important}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.button--quiet{border:0;background:transparent;color:#2e7263;font-weight:800;cursor:pointer}.empty-copy{color:var(--muted);font-size:.85rem}@media(max-width:1050px){.inventory-grid,.inventory-grid--lower{grid-template-columns:1fr}}@media(max-width:640px){.form-grid,.metric-grid{grid-template-columns:1fr}.record-row{grid-template-columns:1fr}.form-grid__wide{grid-column:auto}}`],
})
export class InventoryWorkspaceComponent implements OnInit {
  readonly language = inject(LanguageService); private readonly inventory = inject(InventoryService); private readonly masterData = inject(MasterDataService);
  readonly warehouses = signal<InventoryWarehouseOption[]>([]); readonly products = signal<ProductRecord[]>([]); readonly units = signal<UnitOfMeasureRecord[]>([]); readonly movements = signal<InventoryMovement[]>([]); readonly openings = signal<InventoryOpeningBalance[]>([]); readonly reservations = signal<InventoryReservation[]>([]); readonly transfers = signal<InventoryTransfer[]>([]); readonly availability = signal<InventoryAvailability | null>(null); readonly customerReturnBoundary = signal<InventoryCustomerReturnBoundary | null>(null); readonly error = signal('');
  readonly movementColumns: DataGridColumn<InventoryMovement>[] = [
    { key: 'date', label: this.text('dateColumn'), value: row => row.effectiveDate, filter: 'date-range' },
    { key: 'product', label: this.text('product'), value: row => row.productSku, secondaryText: row => row.productName, filter: 'text' },
    { key: 'direction', label: this.text('sourceType'), value: row => row.direction, badge: true, filter: 'select', filterOptions: [{ value: 'Inbound', label: 'Inbound' }, { value: 'Outbound', label: 'Outbound' }] },
    { key: 'quantity', label: this.text('quantity'), value: row => row.quantity, display: row => row.quantity.toLocaleString(this.language.language()), align: 'end', filter: 'number-range' },
    { key: 'source', label: this.text('sourceReference'), value: row => row.sourceType, secondaryText: row => row.sourceReference ?? '' },
  ];
  readonly openingColumns: DataGridColumn<InventoryOpeningBalance>[] = [
    { key: 'source', label: this.text('sourceSystem'), value: row => row.sourceSystem, filter: 'text' },
    { key: 'warehouse', label: this.text('inventoryTitle'), value: row => row.warehouseCode },
    { key: 'date', label: this.text('dateColumn'), value: row => row.asOfDate, filter: 'date-range' },
    { key: 'quantity', label: this.text('quantity'), value: row => row.validQuantityTotal, display: row => row.validQuantityTotal.toLocaleString(this.language.language()), align: 'end', filter: 'number-range' },
    { key: 'status', label: this.gridLabel('status'), value: row => row.status, badge: true, filter: 'text' },
  ];
  readonly reservationColumns: DataGridColumn<InventoryReservation>[] = [
    { key: 'reference', label: this.text('sourceReference'), value: row => row.sourceReference, filter: 'text' },
    { key: 'product', label: this.text('product'), value: row => row.productSku },
    { key: 'reserved', label: this.text('reserved'), value: row => row.reservedQuantity, display: row => row.reservedQuantity.toLocaleString(this.language.language()), align: 'end', filter: 'number-range' },
    { key: 'unallocated', label: this.text('unallocated'), value: row => row.unallocatedQuantity, display: row => row.unallocatedQuantity.toLocaleString(this.language.language()), align: 'end', filter: 'number-range' },
    { key: 'status', label: this.gridLabel('status'), value: row => row.status, badge: true, filter: 'text' },
  ];
  readonly transferColumns: DataGridColumn<InventoryTransfer>[] = [
    { key: 'route', label: this.movementText('transferTitle'), value: row => `${row.sourceWarehouseCode} → ${row.destinationWarehouseCode}`, filter: 'text' },
    { key: 'product', label: this.text('product'), value: row => row.productSku },
    { key: 'quantity', label: this.text('quantity'), value: row => row.quantity, display: row => row.quantity.toLocaleString(this.language.language()), align: 'end', filter: 'number-range' },
    { key: 'mode', label: this.movementText('transferMode'), value: row => row.mode },
    { key: 'status', label: this.gridLabel('status'), value: row => row.status, badge: true, filter: 'text' },
  ];
  get openingActions() { return [
    { key: 'validate', label: this.text('validate'), visible: (row: InventoryOpeningBalance) => row.status === 'Draft' },
    { key: 'post', label: this.text('post'), visible: (row: InventoryOpeningBalance) => row.status === 'Validated' },
    { key: 'correct', label: this.text('correct'), visible: (row: InventoryOpeningBalance) => row.status === 'Posted' },
  ]; }
  get transferActions() { return [
    { key: 'complete', label: this.text('post'), visible: (row: InventoryTransfer) => row.status === 'Draft' && row.mode === 'Direct' },
    { key: 'ship', label: this.movementText('ship'), visible: (row: InventoryTransfer) => row.status === 'Draft' && row.mode === 'InTransit' },
    { key: 'receive', label: this.movementText('receive'), visible: (row: InventoryTransfer) => row.status === 'Shipped' || row.status === 'PartiallyReceived' },
    { key: 'shortage', label: this.movementText('resolveShortage'), visible: (row: InventoryTransfer) => row.status === 'Shipped' || row.status === 'PartiallyReceived' },
    { key: 'cancel', label: this.text('cancel'), visible: (row: InventoryTransfer) => row.status === 'Draft' },
  ]; }
  gridLabel(key: 'count' | 'filter' | 'all' | 'clear' | 'status'): string {
    const labels = this.language.language() === 'ar'
      ? { count: '\u0633\u062c\u0644\u0627\u062a', filter: '\u062a\u0635\u0641\u064a\u0629', all: '\u0627\u0644\u0643\u0644', clear: '\u0645\u0633\u062d \u0639\u0648\u0627\u0645\u0644 \u0627\u0644\u062a\u0635\u0641\u064a\u0629', status: '\u0627\u0644\u062d\u0627\u0644\u0629' }
      : { count: 'records', filter: 'Filter', all: 'All', clear: 'Clear filters', status: 'Status' };
    return labels[key];
  }
  selectedWarehouseId = ''; selectedProductId = ''; selectedUnitId = ''; opening = { sourceOwner: 'Inventory Operations', sourceSystem: 'Opening Balance Import', asOfDate: new Date().toISOString().slice(0, 10), quantity: 0, unitCost: 0, currencyCode: 'SAR', sourceReference: '' }; reservation = { requestedQuantity: 0, sourceType: 'Demand', sourceReference: '', allowPartialAllocation: true, trackingIdentity: '' }; transfer = { sourceWarehouseId: '', destinationWarehouseId: '', quantity: 0, mode: 'Direct' as 'Direct' | 'InTransit', reason: '' }; reductionQuantities: Record<string, number | null> = {};
  private selectedWarehouse = computed(() => this.warehouses().find(item => item.warehouseId === this.selectedWarehouseId));
  ngOnInit(): void { void this.load(); }
  text(key: Parameters<LanguageService['text']>[0]): string { return this.language.text(key); }
  movementText(key: keyof typeof movementLabels): string { return movementLabels[key][this.language.language()]; }
  trackingEnabled(): boolean { return this.products().find(item => item.id === this.selectedProductId)?.trackingEnabled ?? false; }
  canCreate(): boolean { return !!this.selectedWarehouse() && !!this.selectedProductId && !!this.selectedUnitId && this.opening.quantity > 0 && this.opening.unitCost >= 0 && this.opening.sourceReference.trim().length > 0; }
  canReserve(): boolean { return !!this.selectedWarehouse() && !!this.selectedProductId && !!this.selectedUnitId && this.reservation.requestedQuantity > 0 && !!this.reservation.sourceReference; }
  canCreateTransfer(): boolean { return !!this.selectedWarehouse() && !!this.transfer.sourceWarehouseId && !!this.transfer.destinationWarehouseId && this.transfer.sourceWarehouseId !== this.transfer.destinationWarehouseId && !!this.selectedProductId && !!this.selectedUnitId && this.transfer.quantity > 0; }
  async load(): Promise<void> { try { const [warehouses, products, units] = await Promise.all([firstValueFrom(this.inventory.warehouses()), firstValueFrom(this.masterData.list('products')), firstValueFrom(this.masterData.list('units'))]); this.warehouses.set(warehouses); this.products.set(products.filter((item): item is ProductRecord => 'sku' in item && item.isInventoryRelevant)); this.units.set(units.filter((item): item is UnitOfMeasureRecord => 'code' in item)); if (warehouses[0]) { this.selectedWarehouseId = warehouses[0].warehouseId; this.transfer.sourceWarehouseId = warehouses[0].warehouseId; const product = this.products()[0]; if (product) { this.selectedProductId = product.id; this.selectedUnitId = product.baseUnitOfMeasureId; } await this.onWarehouseChanged(); } this.customerReturnBoundary.set(await firstValueFrom(this.inventory.customerReturnBoundary())); } catch { this.error.set(this.text('networkError')); } }
  async onWarehouseChanged(): Promise<void> { const warehouse = this.selectedWarehouse(); if (!warehouse) return; try { const filters = { warehouseId: warehouse.warehouseId, companyId: warehouse.companyId, branchId: warehouse.branchId || undefined }; const [movements, openings, reservations, transfers] = await Promise.all([firstValueFrom(this.inventory.ledger(filters)), firstValueFrom(this.inventory.openings(filters)), firstValueFrom(this.inventory.reservations(filters)), firstValueFrom(this.inventory.transfers({ companyId: warehouse.companyId, branchId: warehouse.branchId || undefined }))]); this.movements.set(movements); this.openings.set(openings); this.reservations.set(reservations); this.transfers.set(transfers); await this.loadAvailability(); } catch { this.error.set(this.text('networkError')); } }
  async loadAvailability(): Promise<void> { const warehouse = this.selectedWarehouse(); const product = this.products().find(item => item.id === this.selectedProductId); if (!warehouse || !product || !this.selectedUnitId) { this.availability.set(null); return; } try { this.availability.set(await firstValueFrom(this.inventory.availability({ warehouseId: warehouse.warehouseId, companyId: warehouse.companyId, branchId: warehouse.branchId, productId: product.id, unitOfMeasureId: this.selectedUnitId, trackingIdentity: this.trackingEnabled() ? this.reservation.trackingIdentity || undefined : undefined }))); } catch { this.availability.set(null); } }
  // This bounded workspace emits one row. Its user-supplied source reference
  // is the truthful stable line reference; a future multi-row UI must carry a
  // stable source-line reference from the import/source context for each row.
  async createOpening(): Promise<void> { const warehouse = this.selectedWarehouse(); if (!warehouse || !this.canCreate()) return; const sourceReference = this.opening.sourceReference.trim(); const payload: InventoryOpeningCreateRequest = { companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, asOfDate: this.opening.asOfDate, sourceOwner: this.opening.sourceOwner, sourceSystem: this.opening.sourceSystem, extractedAt: new Date().toISOString(), sourceReference, rows: [{ productId: this.selectedProductId, unitOfMeasureId: this.selectedUnitId, quantity: this.opening.quantity, unitCost: this.opening.unitCost, currencyCode: this.opening.currencyCode, trackingIdentity: this.trackingEnabled() ? this.reservation.trackingIdentity || null : null, sourceLineReference: sourceReference }] }; try { await this.inventory.createOpening(payload); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async validateOpening(record: InventoryOpeningBalance): Promise<void> { try { await this.inventory.validateOpening(record.id, record.version); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async postOpening(record: InventoryOpeningBalance): Promise<void> { try { await this.inventory.postOpening(record.id, record.version); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async correctOpening(record: InventoryOpeningBalance): Promise<void> { try { await this.inventory.correctOpening(record.id, record.version, 'Controlled opening-balance correction'); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async createReservation(): Promise<void> { const warehouse = this.selectedWarehouse(); if (!warehouse || !this.canReserve()) return; const payload: InventoryReservationCreateRequest = { companyId: warehouse.companyId, branchId: warehouse.branchId, warehouseId: warehouse.warehouseId, productId: this.selectedProductId, unitOfMeasureId: this.selectedUnitId, requestedQuantity: this.reservation.requestedQuantity, sourceType: this.reservation.sourceType, sourceReference: this.reservation.sourceReference, allowPartialAllocation: this.reservation.allowPartialAllocation, trackingIdentity: this.trackingEnabled() ? this.reservation.trackingIdentity || null : null }; try { await this.inventory.createReservation(payload); await this.onWarehouseChanged(); await this.loadAvailability(); } catch { this.error.set(this.text('requestError')); } }
  async reduceReservation(record: InventoryReservation): Promise<void> { const quantity = this.reductionQuantities[record.id] ?? 0; if (quantity <= 0 || quantity > record.reservedQuantity) return; try { await this.inventory.reduceReservation(record.id, record.version, quantity); delete this.reductionQuantities[record.id]; await this.onWarehouseChanged(); await this.loadAvailability(); } catch { this.error.set(this.text('requestError')); } }
  async releaseReservation(record: InventoryReservation): Promise<void> { try { await this.inventory.releaseReservation(record.id, record.version); await this.onWarehouseChanged(); await this.loadAvailability(); } catch { this.error.set(this.text('requestError')); } }
  async createTransfer(): Promise<void> { const source = this.warehouses().find(item => item.warehouseId === this.transfer.sourceWarehouseId); if (!source || !this.canCreateTransfer()) return; const payload: InventoryTransferCreateRequest = { companyId: source.companyId, branchId: source.branchId, sourceWarehouseId: this.transfer.sourceWarehouseId, destinationWarehouseId: this.transfer.destinationWarehouseId, productId: this.selectedProductId, unitOfMeasureId: this.selectedUnitId, quantity: this.transfer.quantity, mode: this.transfer.mode, trackingIdentity: this.trackingEnabled() ? this.reservation.trackingIdentity || null : null, reason: this.transfer.reason.trim() || null }; try { await this.inventory.createTransfer(payload); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async completeDirect(record: InventoryTransfer): Promise<void> { try { await this.inventory.completeDirectTransfer(record.id, record.version); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async ship(record: InventoryTransfer): Promise<void> { try { await this.inventory.shipTransfer(record.id, record.version); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async receive(record: InventoryTransfer): Promise<void> { const quantity = Number(globalThis.prompt(this.movementText('receiveQuantity'))); if (!Number.isFinite(quantity) || quantity <= 0) return; try { await this.inventory.receiveTransfer(record.id, record.version, { quantity, reference: `receipt-${Date.now().toString(36)}` }); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async resolveShortage(record: InventoryTransfer): Promise<void> { try { await this.inventory.resolveTransferShortage(record.id, record.version, { reference: `loss-${Date.now().toString(36)}` }); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  async cancelTransfer(record: InventoryTransfer): Promise<void> { try { await this.inventory.cancelTransfer(record.id, record.version, { reason: 'Cancelled before shipment' }); await this.onWarehouseChanged(); } catch { this.error.set(this.text('requestError')); } }
  runOpeningAction(action: DataGridAction<InventoryOpeningBalance>): void { if (action.action === 'validate') void this.validateOpening(action.row); else if (action.action === 'post') void this.postOpening(action.row); else if (action.action === 'correct') void this.correctOpening(action.row); }
  runTransferAction(action: DataGridAction<InventoryTransfer>): void { if (action.action === 'complete') void this.completeDirect(action.row); else if (action.action === 'ship') void this.ship(action.row); else if (action.action === 'receive') void this.receive(action.row); else if (action.action === 'shortage') void this.resolveShortage(action.row); else if (action.action === 'cancel') void this.cancelTransfer(action.row); }
}
